# Generated by Django 4.0.5 on 2022-06-30 12:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_like_alter_listing_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 30, 12, 38, 0, 96615, tzinfo=utc), editable=False),
        ),
    ]
