# Generated by Django 4.0.5 on 2022-07-04 13:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_like_liked_by_like_listing_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='liked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lover', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 4, 13, 39, 7, 164208, tzinfo=utc), editable=False),
        ),
    ]
